import Image from 'next/image';
import Link from 'next/link';

export default function Home(){return <main>
  <section className="hero vmv-hero"><div className="hero-copy"><div className="eyebrow"><span className="signal-dot"/> Connected worksite safety</div><h1>Protect people.<br/><span>Strengthen every site.</span></h1><p className="lead">Shield X gives construction teams one clear system for workforce access, helmet and safety-vest visibility, attendance and safety accountability—from the office to the field.</p><div className="actions"><Link className="button" href="/register">Get Started <span>→</span></Link><Link className="text-link" href="/pricing">View Pricing</Link><Link className="text-link" href="/login">Login</Link></div><div className="trust-row"><span>Verified payments</span><span>Signed licenses</span><span>Role-based access</span></div></div>
    <div className="hero-console"><div className="console-top"><span>SHIELD X / LIVE OVERVIEW</span><span className="live-pill">● SYSTEM READY</span></div><div className="console-focus"><span>Workforce protection</span><strong>One connected<br/>safety chain.</strong></div><div className="console-grid"><div><small>ADMIN</small><b>Control</b></div><div><small>SUPERVISOR</small><b>Monitor</b></div><div><small>WORKER</small><b>Protect</b></div></div><div className="hazard-stripe"/></div>
  </section>

  <section id="products" className="section product-overview"><div className="section-heading"><div><div className="eyebrow">Purpose-built protection</div><h2>See the risks that matter on site.</h2></div><p>Shield X connects PPE monitoring, actionable safety alerts and role-controlled workforce access without breaking the chain of responsibility.</p></div><div className="capability-grid"><article><span className="capability-code">PPE 01</span><h3>Helmet monitoring</h3><p>Supervisors can review the helmet status of workers assigned to them and respond when protection is missing.</p></article><article><span className="capability-code">PPE 02</span><h3>Safety-vest monitoring</h3><p>High-visibility vest status is presented within the supervised worker workflow for clear site accountability.</p></article><article><span className="capability-code">ALERT 03</span><h3>Safety alerts</h3><p>Supervisors receive operational alerts, while workers receive safety notifications relevant to their own status.</p></article></div></section>

  <section id="process" className="section process-section journey-section"><div className="journey-heading"><div className="eyebrow">How it works</div><h2>From registration to a safer workforce.</h2><p>Four clear steps take your organization from secure onboarding to an active, connected safety team.</p></div><div className="journey-grid">
    <article className="journey-step"><div className="step-badge"><span>01</span></div><h3>Create your organization</h3><p>Add your company, administrator and primary worksite details.</p></article><div className="journey-arrow" aria-hidden="true"><svg viewBox="0 0 100 45"><path d="M4 28c24 16 54 14 82-10"/><path d="m76 14 12 3-2 12"/></svg></div>
    <article className="journey-step"><div className="step-badge"><span>02</span></div><h3>Select and pay</h3><p>Choose the right plan and complete secure, verified UPI checkout.</p></article><div className="journey-arrow arrow-down" aria-hidden="true"><svg viewBox="0 0 100 45"><path d="M4 20c27-15 57-11 83 10"/><path d="m78 31 11 1-1-12"/></svg></div>
    <article className="journey-step"><div className="step-badge"><span>03</span></div><h3>Receive your license</h3><p>Your organization license is digitally signed and delivered by email.</p></article><div className="journey-arrow" aria-hidden="true"><svg viewBox="0 0 100 45"><path d="M4 28c24 16 54 14 82-10"/><path d="m76 14 12 3-2 12"/></svg></div>
    <article className="journey-step"><div className="step-badge"><span>04</span></div><h3>Build your team</h3><p>Admins invite supervisors, then supervisors securely onboard workers.</p></article>
  </div></section>

  <section id="about" className="section company-section"><div className="company-logo"><Image src="/vmv-nexus.jpeg" alt="VMV Nexus Safety Solutions" width={1536} height={1024} priority/></div><div><div className="eyebrow">The company behind Shield X</div><h2>Developed by VMV Nexus Safety Solutions.</h2><p className="lead">VMV Nexus builds practical safety technology for real industrial environments. Shield X combines secure digital access with a clear operational workflow designed around how safety teams actually work.</p><div className="company-values"><span>Safety-first</span><span>Field-ready</span><span>Professionally supported</span></div></div></section>

  <section className="section leadership-section"><div className="leadership-heading"><div><div className="eyebrow">Our Members</div><h2>Meet the leadership behind VMV Nexus.</h2></div><p>Five complementary leaders bringing together business strategy, financial stewardship, technology vision and technical delivery.</p></div><div className="leadership-grid"><article className="leader-card"><div className="leader-top"><span className="leader-initials">VP</span></div><div className="leader-info"><h3>Vaibhav Purushotham</h3><span>CEO &amp; COO</span><p>Leads company strategy and operations, aligning partnerships, teams and execution with the VMV Nexus vision.</p></div></article><article className="leader-card"><div className="leader-top"><span className="leader-initials">VM</span></div><div className="leader-info"><h3>Vishnu Manikandan</h3><span>Chief Financial Officer</span><p>Directs financial planning and governance to support responsible growth and sustainable product development.</p></div></article><article className="leader-card"><div className="leader-top"><span className="leader-initials">MM</span></div><div className="leader-info"><h3>Madhumitha Muniyandi</h3><span>Chief Technology Officer</span><p>Guides product architecture and engineering standards behind secure, dependable Shield X experiences.</p></div></article><article className="leader-card"><div className="leader-top"><span className="leader-initials">SL</span></div><div className="leader-info"><h3>Srinath L</h3><span>Technical Director</span><p>Oversees technical delivery, system integration and implementation quality through field deployment.</p></div></article><article className="leader-card"><div className="leader-top"><span className="leader-initials">GCS</span></div><div className="leader-info"><h3>Gnana Catherine Sylvia D</h3><span>Technical Head</span><p>Leads technical coordination, engineering execution and quality practices across product development and implementation.</p></div></article></div></section>

  <section className="cta-section shieldx-watermark"><svg className="watermark-shield" viewBox="0 0 32 36" aria-hidden="true"><path d="M16 2.5 28 7v9.2c0 8.1-4.8 14.1-12 17.3C8.8 30.3 4 24.3 4 16.2V7l12-4.5Z"/></svg><div className="watermark-copy"><span>START WITH SHIELD X</span><h2>Build a safer organization from day one.</h2><p>Create your company workspace, activate a signed license and begin onboarding your safety team.</p></div><Link className="button light-button watermark-button" href="/register">Create your organization <span aria-hidden="true">→</span></Link></section>
</main>}
