'use client';
import { FormEvent,useEffect,useState } from 'react';

type Result={message:string;activationUrl?:string;emailDelivered?:boolean};

export default function Invite(){
  const [result,setResult]=useState<Result|null>(null);
  const [busy,setBusy]=useState(false);
  const [sites,setSites]=useState<Array<{id:string;name:string;zones:Array<{id:string;name:string}>}>>([]);
  useEffect(()=>{fetch('/api/sites').then(response=>response.json()).then(data=>setSites(data.sites??[])).catch(()=>{})},[]);
  async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setResult({message:'Creating secure invitation…'});const res=await fetch('/api/invitations',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(Object.fromEntries(new FormData(e.currentTarget)))});const out=await res.json();if(!res.ok)setResult({message:out.error});else setResult({message:out.emailDelivered?'Invitation sent successfully.':'Test invitation created. Resend delivery was skipped.',activationUrl:out.activationUrl,emailDelivered:out.emailDelivered});setBusy(false)}
  return <main className="form-shell"><form className="form-card" onSubmit={submit}><div className="eyebrow">Controlled onboarding</div><h1>Invite the next person.</h1><p>The backend determines the invitation role from your authenticated account: Admins authorize Supervisors, while Supervisors onboard Workers.</p><div className="notice"><strong>Invitations are for new accounts only.</strong><p>If a Supervisor already exists and needs a different site, go to Admin → Supervisors and choose Change site.</p></div><div className="form-grid"><div className="field"><label>Full name</label><input name="name" required/></div><div className="field"><label>Email</label><input name="email" type="email" required/></div><div className="field"><label>Phone</label><input name="phone" required/></div><div className="field"><label>Assigned site</label><select name="siteId" required><option value="">Select an authorized site</option>{sites.map(site=><option value={site.id} key={site.id}>{site.name}</option>)}</select></div><div className="field"><label>Assigned zone (workers only)</label><select name="zoneId"><option value="">Select a zone if applicable</option>{sites.flatMap(site=>site.zones).map(zone=><option value={zone.id} key={zone.id}>{zone.name}</option>)}</select></div><div className="field"><label>Shift (workers only)</label><input name="shift" placeholder="Example: Day shift"/></div><div className="field full"><label>Worker code (workers only)</label><input name="workerCode" placeholder="Example: CHN-WRK-001"/></div></div>{result&&<div className="notice"><strong>{result.message}</strong>{result.activationUrl&&<><p>This activation link is shown only during local development:</p><a className="button" href={result.activationUrl}>Open activation page →</a></>}</div>}<button className="button" disabled={busy}>{busy?'Creating invitation…':'Send secure invitation'}</button></form></main>
}
