import Link from 'next/link';
import { ensurePlans } from '@/lib/plans';

const presentation = [
  { id:'basic', name:'Foundation', price:'4,999', description:'For focused teams running safety operations at one active site.', supervisors:'2', workers:'20', sites:'1', accent:'foundation', features:['Signed organization license','Supervisor desktop access','Worker mobile access','Secure email invitations','Organization audit history'] },
  { id:'professional', name:'Operations', price:'12,999', description:'For growing organizations that need visibility across several teams and sites.', supervisors:'10', workers:'100', sites:'5', accent:'operations', recommended:true, features:['Everything in Foundation','Expanded team capacity','Multi-site organization control','Priority safety workflows','Complete audit visibility'] },
  { id:'enterprise', name:'Enterprise', price:'29,999', description:'For large industrial operations managing a broad, distributed workforce.', supervisors:'50', workers:'500', sites:'25', accent:'enterprise', features:['Everything in Operations','High-capacity workforce access','Large multi-site deployment','Enterprise role governance','Priority onboarding support'] },
];

function Check(){return <svg viewBox="0 0 20 20" aria-hidden="true"><path d="m4 10 4 4 8-9"/></svg>}

export const dynamic='force-dynamic';
export default async function Pricing(){const configured=await ensurePlans();const plans=presentation.map(item=>{const stored=configured.find(plan=>plan.id===item.id);return {...item,price:stored?(stored.pricePaise/100).toLocaleString('en-IN'):item.price,supervisors:String(stored?.maxSupervisors??item.supervisors),workers:String(stored?.maxWorkers??item.workers),sites:String(stored?.maxSites??item.sites),features:stored?.features.length?stored.features:item.features}});return <main className="pricing-page">
  <section className="pricing-hero"><Link className="pricing-back" href="/" aria-label="Back to home"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="m15 18-6-6 6-6"/></svg><span>Back to home</span></Link><div className="eyebrow">Flexible plans for safer worksites</div><h1>Protection that scales<br/>with every site.</h1><p>Choose the capacity your organization needs today. Every plan includes the secure Shield X licensing and onboarding workflow.</p><div className="billing-note"><span>Annual billing</span><small>One verified payment · No hidden platform fees</small></div></section>

  <section className="pricing-plans" aria-label="Shield X subscription plans">{plans.map(plan=><article className={`pricing-card ${plan.accent} ${plan.recommended?'recommended':''}`} key={plan.id}>{plan.recommended&&<div className="recommended-label">MOST POPULAR</div>}<header><div><span className="plan-index">0{plans.indexOf(plan)+1}</span><h2>{plan.name}</h2></div><p>{plan.description}</p></header><div className="plan-price"><span>₹</span><strong>{plan.price}</strong><div><small>INR</small><b>/ year</b></div></div><div className="capacity-grid"><div><strong>{plan.supervisors}</strong><span>Supervisors</span></div><div><strong>{plan.workers}</strong><span>Workers</span></div><div><strong>{plan.sites}</strong><span>{plan.sites==='1'?'Site':'Sites'}</span></div></div><div className="feature-block"><span>WHAT&apos;S INCLUDED</span><ul>{plan.features.map(feature=><li key={feature}><Check/>{feature}</li>)}</ul></div><Link className="plan-button" href={`/register?plan=${plan.id}`}>Choose {plan.name}<span>→</span></Link></article>)}</section>

  <section className="pricing-faq"><div><div className="eyebrow">Before you choose</div><h2>Pricing questions,<br/>answered clearly.</h2><p>Need help selecting capacity? The Operations plan is the strongest fit for most multi-team organizations.</p></div><div className="faq-list"><details><summary>What happens after payment?<span>+</span></summary><p>After Razorpay verifies your payment, Shield X creates your subscription, signs your organization license and emails the license to your administrator.</p></details><details><summary>Can an Admin add workers directly?<span>+</span></summary><p>No. Shield X preserves accountability: Admins invite Supervisors, and activated Supervisors invite the Workers assigned to them.</p></details><details><summary>Are desktop and mobile access included?<span>+</span></summary><p>Yes. Every tier includes access for the Supervisor desktop and Worker mobile experiences within the plan capacity.</p></details><details><summary>Which plan is best for multiple sites?<span>+</span></summary><p>Operations supports up to five sites and is recommended for growing companies. Enterprise supports up to twenty-five sites.</p></details></div></section>

  <section className="pricing-cta"><div><span>SHIELD X</span><h2>Ready to protect your workforce?</h2><p>Create your organization and activate your signed safety license.</p></div><Link href="/register">Get started <span>→</span></Link></section>
</main>}
